class YouTubeClient:
    def __init__(self, read_service, write_service):
        self.read_service = read_service
        self.write_service = write_service

    def get_related_videos(self, video_id, max_results=10):
        # Hinweis: relatedToVideoId wird von der YouTube API v3 oft eingeschränkt.
        # Wir versuchen es erst, und wenn es leer ist oder fehlschlägt, nutzen wir den Fallback.
        try:
            request = self.read_service.search().list(
                part="snippet",
                relatedToVideoId=video_id,
                type="video",
                maxResults=max_results,
                videoCategoryId="10"
            )
            response = request.execute()
            ids = [item['id']['videoId'] for item in response.get('items', [])]
            if not ids:
                raise Exception("Empty results for relatedToVideoId")
            return ids
        except Exception:
            # Fallback: Suche nach dem Video-Titel + "music"
            video_info = self.read_service.videos().list(part="snippet", id=video_id).execute()
            title = video_info['items'][0]['snippet']['title']
            print(f"Fallback-Suche für: {title}")
            request = self.read_service.search().list(
                part="snippet",
                q=f"{title} mix",
                type="video",
                maxResults=max_results,
                videoCategoryId="10"
            )
            response = request.execute()
            return [item['id']['videoId'] for item in response.get('items', [])]

    def create_playlist(self, title, description="Generated by Smart Creator"):
        request = self.write_service.playlists().insert(
            part="snippet,status",
            body={
              "snippet": {
                "title": title,
                "description": description
              },
              "status": {
                "privacyStatus": "private"
              }
            }
        )
        response = request.execute()
        return response['id']

    def add_to_playlist(self, playlist_id, video_id):
        request = self.write_service.playlistItems().insert(
            part="snippet",
            body={
                "snippet": {
                    "playlistId": playlist_id,
                    "resourceId": {
                        "kind": "youtube#video",
                        "videoId": video_id
                    }
                }
            }
        )
        return request.execute()
