use serde::{Deserialize, Serialize};
use std::fmt;

/// Style for the audio meter
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum AudioMeterStyle {
    #[default]
    Retro,
    Digital,
}

impl fmt::Display for AudioMeterStyle {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Retro => write!(f, "Retro (Analog)"),
            Self::Digital => write!(f, "Digital (LED)"),
        }
    }
}

/// Anzeige-Modus für Toolbar-Metriken.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum ToolbarMetricMode {
    /// Immer sichtbar.
    #[default]
    Always,
    /// Nur via Hover/Popover sichtbar.
    Hover,
}

/// Konfiguration für eine einzelne Toolbar-Metrik.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolbarMetricConfig {
    /// Ob die Metrik angezeigt wird.
    #[serde(default = "default_true")]
    pub visible: bool,
    /// Anzeige-Modus der Metrik.
    #[serde(default)]
    pub mode: ToolbarMetricMode,
}

impl Default for ToolbarMetricConfig {
    fn default() -> Self {
        Self { visible: true, mode: ToolbarMetricMode::Always }
    }
}

fn default_true() -> bool {
    true
}

/// Konfiguration aller Toolbar-Metriken.
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub struct ToolbarMetricsConfig {
    #[serde(default)]
    pub bpm: ToolbarMetricConfig,
    #[serde(default)]
    pub audio_meter: ToolbarMetricConfig,
    #[serde(default)]
    pub status: ToolbarMetricConfig,
    #[serde(default)]
    pub fps: ToolbarMetricConfig,
    #[serde(default)]
    pub frame_time: ToolbarMetricConfig,
    #[serde(default)]
    pub cpu: ToolbarMetricConfig,
    #[serde(default)]
    pub gpu: ToolbarMetricConfig,
    #[serde(default)]
    pub ram: ToolbarMetricConfig,
}

/// Vertical Synchronization Mode
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum VSyncMode {
    #[default]
    Auto,
    On,
    Off,
}

impl fmt::Display for VSyncMode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Auto => write!(f, "Auto"),
            Self::On => write!(f, "On (VSync)"),
            Self::Off => write!(f, "Off (No Limit)"),
        }
    }
}

/// Application log level used for console and file logging.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum AppLogLevel {
    #[default]
    Info,
    Debug,
}

impl AppLogLevel {
    /// Returns the serialized string representation used by the core LogConfig.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Info => "info",
            Self::Debug => "debug",
        }
    }
}

impl fmt::Display for AppLogLevel {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Info => write!(f, "Info"),
            Self::Debug => write!(f, "Debug"),
        }
    }
}

/// Globales Animationsprofil für UI-Bewegungen.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum AnimationProfile {
    /// Animationen deaktiviert.
    Off,
    /// Subtile Animationen (Standard).
    #[default]
    Subtle,
    /// Cinematische Animationen mit stärkerem Effekt.
    Cinematic,
}

impl fmt::Display for AnimationProfile {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Off => write!(f, "Off"),
            Self::Subtle => write!(f, "Subtle"),
            Self::Cinematic => write!(f, "Cinematic"),
        }
    }
}

/// Configuration for Philips Hue integration
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct HueConfig {
    /// Bridge IP address
    #[serde(default)]
    pub bridge_ip: String,
    /// Whitelisted username (generated by bridge)
    #[serde(default)]
    pub username: String,
    /// DTLS Client Key (generated by bridge for Entertainment API)
    #[serde(default)]
    pub client_key: String,
    /// Selected Entertainment Area ID
    #[serde(default)]
    pub entertainment_area: String,
    /// Setup mode/auto-connect
    #[serde(default)]
    pub auto_connect: bool,
}
